---

  - name: test if service sshd exists
    stat: path=/etc/init.d/ssh
    register: ssh_installed
  - name: Place my public ssh key
    authorized_key: user="{{ ansible_user_id }}" key="{{ lookup('file', 'authorized_keys.myuser.pub') }}"
    when: ssh_installed.stat.exists
  - name: Disable password login
    become: yes
    replace: dest={{ sshd_config }} regexp="#PasswordAuthentication yes" replace="PasswordAuthentication no"
    when: ssh_installed.stat.exists
    notify:
      - restart sshd
