---

 - name: install ubuntu gnome desktop
   become: yes
   apt: name=ubuntu-gnome-desktop state=latest
      
 - name: active dark theme for all gtk applications
   copy: src='settings.ini' dest='{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini'

 - name: active extensions alternative tab and launch new instance
   command: gsettings set org.gnome.shell enabled-extensions "['alternate-tab@gnome-shell-extensions.gcampax.github.com', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com']"

 - name: active week numbers in calendar applet
   command: gsettings set org.gnome.desktop.calendar show-weekdate true

 - name: disable horrible ubuntu colortheme for login screen
   become: yes
   command: update-alternatives --set gdm3.css /usr/share/gnome-shell/theme/gnome-shell.css
